In [2]:
import pandas as pd
df = pd.read_excel("./Adidas_Sales_Data.xlsx")

In [3]:
df.head()

,Retailer,Retailer ID,Invoice Date,Region,State,City,Gender Type,Product Category,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,11234,2021-10-26,Northeast,Pennsylvania,Philadelphia,Men,Apparel,55,125,6875,2406.25,0.35,Outlet
1,Foot Locker,11234,2021-10-27,Northeast,Pennsylvania,Philadelphia,Women,Apparel,45,225,10125,3037.50,0.30,Outlet
2,Foot Locker,11234,2021-10-28,Northeast,Pennsylvania,Philadelphia,Men,Street Footwear,45,475,21375,11756.25,0.55,Outlet
3,Foot Locker,11234,2021-10-29,Northeast,Pennsylvania,Philadelphia,Men,Athletic Footwear,45,125,5625,1968.75,0.35,Outlet
4,Foot Locker,11234,2021-10-30,Northeast,Pennsylvania,Philadelphia,Women,Street Footwear,35,175,6125,2450.00,0.40,Outlet

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Retailer          9648 non-null   object
 1   Retailer ID       9648 non-null   int64
 2   Invoice Date      9648 non-null   datetime64[ns]
 3   Region            9648 non-null   object
 4   State             9648 non-null   object
 5   City              9648 non-null   object
 6   Gender Type       9648 non-null   object
 7   Product Category  9648 non-null   object
 8   Price per Unit    9648 non-null   int64
 9   Units Sold        9648 non-null   int64
 10  Total Sales       9648 non-null   int64
 11  Operating Profit  9648 non-null   float64
 12  Operating Margin  9648 non-null   float64
 13  Sales Method      9648 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(4), object(7)
memory usage: 1.0+ MB

In [5]:
df.describe(include='all')

,Retailer,Retailer ID,Invoice Date,Region,State,City,Gender Type,Product Category,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
count,9648,9648.000000,9648,9648,9648,9648,9648,9648,9648.000000,9648.000000,9648.000000,9648.000000,9648.000000,9648
unique,6,NaN,NaN,5,50,52,2,3,NaN,NaN,NaN,NaN,NaN,3
top,Foot Locker,NaN,NaN,West,California,Portland,Men,Street Footwear,NaN,NaN,NaN,NaN,NaN,Online
freq,2637,NaN,NaN,2448,432,360,4826,3218,NaN,NaN,NaN,NaN,NaN,4889
mean,NaN,24858.899461,2021-05-10 15:20:44.776119552,NaN,NaN,NaN,NaN,NaN,45.216625,256.930037,12455.083955,4894.793501,0.422991,NaN
min,NaN,11234.000000,2020-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,7.000000,0.000000,0.000000,0.000000,0.100000,NaN
25%,NaN,11234.000000,2021-02-17 00:00:00,NaN,NaN,NaN,NaN,NaN,35.000000,106.000000,4065.250000,1753.440000,0.350000,NaN
50%,NaN,32145.000000,2021-06-04 00:00:00,NaN,NaN,NaN,NaN,NaN,45.000000,176.000000,7803.500000,3262.980000,0.410000,NaN
75%,NaN,34678.000000,2021-09-16 00:00:00,NaN,NaN,NaN,NaN,NaN,55.000000,350.000000,15864.500000,6192.360000,0.490000,NaN
max,NaN,45679.000000,2021-12-31 00:00:00,NaN,NaN,NaN,NaN,NaN,110.000000,1275.000000,82500.000000,39000.000000,0.800000,NaN
std,NaN,11430.567066,NaN,NaN,NaN,NaN,NaN,NaN,14.705397,214.252030,12716.392111,4866.464372,0.097197,NaN

In [6]:
df.isnull().sum()

Retailer            0
Retailer ID         0
Invoice Date        0
Region              0
State               0
City                0
Gender Type         0
Product Category    0
Price per Unit      0
Units Sold          0
Total Sales         0
Operating Profit    0
Operating Margin    0
Sales Method        0
dtype: int64

In [7]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [8]:
df.columns

Index(['retailer', 'retailer_id', 'invoice_date', 'region', 'state', 'city',
       'gender_type', 'product_category', 'price_per_unit', 'units_sold',
       'total_sales', 'operating_profit', 'operating_margin', 'sales_method'],
      dtype='object')

### Feature Engineering

#### Converting Date Column

In [9]:
df['invoice_date']=pd.to_datetime(df['invoice_date'])

#### Date Features

In [10]:
df['year']=df['invoice_date'].dt.year
df['month']=df['invoice_date'].dt.month
df['day']=df['invoice_date'].dt.day
df['day_of_week']=df['invoice_date'].dt.dayofweek
df['day_name']=df['invoice_date'].dt.day_name()
df['week_of_year']=df['invoice_date'].dt.isocalendar().week
df['quarter']=df['invoice_date'].dt.quarter
df['is_weekend']=df['day_of_week'].isin([5,6]).astype(int)

In [11]:
df.head

<bound method NDFrame.head of          retailer  retailer_id invoice_date     region         state  \
0     Foot Locker        11234   2021-10-26  Northeast  Pennsylvania
1     Foot Locker        11234   2021-10-27  Northeast  Pennsylvania
2     Foot Locker        11234   2021-10-28  Northeast  Pennsylvania
3     Foot Locker        11234   2021-10-29  Northeast  Pennsylvania
4     Foot Locker        11234   2021-10-30  Northeast  Pennsylvania
...           ...          ...          ...        ...           ...
9643    West Gear        32145   2020-03-14       West        Nevada
9644    West Gear        32145   2020-03-15       West        Nevada
9645    West Gear        32145   2020-03-16       West        Nevada
9646    West Gear        32145   2020-03-17       West        Nevada
9647    West Gear        32145   2020-03-18       West        Nevada

              city gender_type   product_category  price_per_unit  units_sold  \
0     Philadelphia         Men            Apparel              55         125
1     Philadelphia       Women            Apparel              45         225
2     Philadelphia         Men    Street Footwear              45         475
3     Philadelphia         Men  Athletic Footwear              45         125
4     Philadelphia       Women    Street Footwear              35         175
...            ...         ...                ...             ...         ...
9643     Las Vegas       Women            Apparel              56         170
9644     Las Vegas         Men    Street Footwear              20         149
9645     Las Vegas         Men  Athletic Footwear              31         145
9646     Las Vegas       Women    Street Footwear              26         128
9647     Las Vegas       Women  Athletic Footwear              26          96

      ...  operating_margin  sales_method  year month  day  day_of_week  \
0     ...              0.35        Outlet  2021    10   26            1
1     ...              0.30        Outlet  2021    10   27            2
2     ...              0.55        Outlet  2021    10   28            3
3     ...              0.35        Outlet  2021    10   29            4
4     ...              0.40        Outlet  2021    10   30            5
...   ...               ...           ...   ...   ...  ...          ...
9643  ...              0.18        Outlet  2020     3   14            5
9644  ...              0.40        Outlet  2020     3   15            6
9645  ...              0.25        Outlet  2020     3   16            0
9646  ...              0.42        Outlet  2020     3   17            1
9647  ...              0.34        Outlet  2020     3   18            2

       day_name  week_of_year quarter  is_weekend
0       Tuesday            43       4           0
1     Wednesday            43       4           0
2      Thursday            43       4           0
3        Friday            43       4           0
4      Saturday            43       4           1
...         ...           ...     ...         ...
9643   Saturday            11       1           1
9644     Sunday            11       1           1
9645     Monday            12       1           0
9646    Tuesday            12       1           0
9647  Wednesday            12       1           0

[9648 rows x 22 columns]>

#### Revenue Based Features

In [12]:
# Average Profit Per Unit
df['profit_per_unit']=df['operating_profit']/df['units_sold']

# Revenue Per Unit 
df['sales_per_unit']=df['total_sales']/df['units_sold']

In [13]:
df.head()

,retailer,retailer_id,invoice_date,region,state,city,gender_type,product_category,price_per_unit,units_sold,...,year,month,day,day_of_week,day_name,week_of_year,quarter,is_weekend,profit_per_unit,sales_per_unit
0,Foot Locker,11234,2021-10-26,Northeast,Pennsylvania,Philadelphia,Men,Apparel,55,125,...,2021,10,26,1,Tuesday,43,4,0,19.25,55.0
1,Foot Locker,11234,2021-10-27,Northeast,Pennsylvania,Philadelphia,Women,Apparel,45,225,...,2021,10,27,2,Wednesday,43,4,0,13.50,45.0
2,Foot Locker,11234,2021-10-28,Northeast,Pennsylvania,Philadelphia,Men,Street Footwear,45,475,...,2021,10,28,3,Thursday,43,4,0,24.75,45.0
3,Foot Locker,11234,2021-10-29,Northeast,Pennsylvania,Philadelphia,Men,Athletic Footwear,45,125,...,2021,10,29,4,Friday,43,4,0,15.75,45.0
4,Foot Locker,11234,2021-10-30,Northeast,Pennsylvania,Philadelphia,Women,Street Footwear,35,175,...,2021,10,30,5,Saturday,43,4,1,14.00,35.0

In [16]:
df.columns

Index(['retailer', 'retailer_id', 'invoice_date', 'region', 'state', 'city',
       'gender_type', 'product_category', 'price_per_unit', 'units_sold',
       'total_sales', 'operating_profit', 'operating_margin', 'sales_method',
       'year', 'month', 'day', 'day_of_week', 'day_name', 'week_of_year',
       'quarter', 'is_weekend', 'profit_per_unit', 'sales_per_unit'],
      dtype='object')

## Database

In [14]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\enbas\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\enbas\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\enbas\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\enbas\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [15]:
from sqlalchemy import create_engine

# Step 1 : Connect to PostgreSQL
username = "postgres"
password = "Enba"
host = "localhost"
port = "5432"
database = "Adidas_Sales"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2 : Load Dataframe into Postgresql
table_name = "customer"
df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"Data Successfully Loaded into Table '{table_name}' in database '{database}'.")

Data Successfully Loaded into Table 'customer' in database 'Adidas_Sales'.